name: Update the alt lists
on: [push, workflow_dispatch]
jobs:
  mkalt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build
      run: |
        python update.py
    - uses: EndBug/add-and-commit@v7.2.1
      with:
        author_name: iam-py-test
        author_email: 84232764+iam-py-test@users.noreply.github.com
        message: '[bot] Auto-update alt list'
