name: Update the alt lists
on: [push, workflow_dispatch]
jobs:
  mkalt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build
      run: |
        python update.py
    - name: Commit & Push
      uses: actions-x/commit@v2
      with:
          email: noreply@example.com
          name: Update bot
          branch: master
