name: Update the alt lists
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  mkalt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Build
      run: |
        curl https://raw.githubusercontent.com/iam-py-test/vxvault_filter/main/ubolist.txt > special_lists/mirrored/vxvault_filter.txt
        pip3 install publicsuffixlist idna requests
        ls -la
        pwd
        ls -laR "Alternative list formats"
        ps -e
        python scripts/update.py
        python scripts/update_total.py
        python scripts/update-duckduckgo-clean-up.py
        python scripts/update-brave-clean-up.py 
        python scripts/create-lite.py
        python scripts/lint.py
        python scripts/checksum.py
        python scripts/mwb_parts.py antimalware.txt "Alternative list formats/mwb_parts"
    - name: Commit & Push
      uses: actions-x/commit@v6
      with:
          email: noreply@example.com
          name: Update bot
          branch: main
          message: Update alt lists
